### ISSUE TITLE
Can this library support multiple 7-segment ?

### ISSUE THREAD

**Issue by HamzaHajeir** [Andy4495/LED744511#1]
HI

Nice work Andy!

I am wondering that if it possible to control over lets say 8 to 12 pieces of 7-segment display using this library.

Greetings 
Hamza

**Comment by Andy4495** [comment]
Hi Hamza - Each instance of the LED744511 class can support up to two 7-segment digits. So in order to control 8 digits, you would  need to create four LED744511 objects (e.g. myLED12, myLED34, myLED56, myLED78). Each of those objects could share the 4 control lines BCD0 - BCD3, but you would need a separate latch enable signal for each digit. Please note that I have not tested a setup using this library with more that 2 digits. 

When I was creating the library for a project I was working on, I ended up stopping at 2 digits because it seems like the LED modules that contain more than 2 digits end up multiplexing the digits, so that you don't have direct control over every segment and need to use a different approach to control the segments. 

-- Andy

**Comment by HamzaHajeir** [comment]
Nice, I'll give it a try.

I guess sharing object's pins to another object would cause a conflict. 
but surely i'll give you feedback when i test it ;)

**Comment by Andy4495** [comment]
Issue closed due to lack of response. Re-open if you have further questions or comments.
